In [11]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt



In [12]:
X = np.array([
    [1, 2, 3],
    [2, 1, 0],
    [4, 5, 6]
])

print("Original Dataset:\n")
print(X)
print(f"size of the dataset: {X.shape}")

Original Dataset:

[[1 2 3]
 [2 1 0]
 [4 5 6]]
size of the dataset: (3, 3)


In [13]:
mean = np.mean(X, axis=0)

print("\nMean of each column:\n")
print(mean)


Mean of each column:

[2.33333333 2.66666667 3.        ]


In [15]:
X_centered = X - mean

print("\nMean Centered Data:\n")
print(X_centered)
print(f"shape of the dataset: {X_centered.shape}")


Mean Centered Data:

[[-1.33333333 -0.66666667  0.        ]
 [-0.33333333 -1.66666667 -3.        ]
 [ 1.66666667  2.33333333  3.        ]]
shape of the dataset: (3, 3)


In [16]:
cov_variance_matrix = np.cov(X_centered)
print("\nCovariance Matrix:\n")
print(cov_variance_matrix)
print(f"shape of the dataset: {cov_variance_matrix.shape}")


Covariance Matrix:

[[ 0.44444444 -0.88888889  0.44444444]
 [-0.88888889  1.77777778 -0.88888889]
 [ 0.44444444 -0.88888889  0.44444444]]
shape of the dataset: (3, 3)


In [20]:
eigenvalues, eigenvectors = np.linalg.eig(cov_variance_matrix)
print("\nEigenvalues:\n")
print(eigenvalues)
print("\nEigenvectors:\n")
print(eigenvectors)

sort_eigenvalues = np.argsort(eigenvalues)[::-1]
# argsort returns the indices that would sort the array. [::-1] reverses the order to get descending order.
print("\nEigenvectors in descending order:\n")
print(sort_eigenvalues)
sorted_eigenvectors = eigenvectors[:, sort_eigenvalues]
print(sorted_eigenvectors)





Eigenvalues:

[ 2.66666667e+00 -6.95310622e-17  2.22837471e-18]

Eigenvectors:

[[ 0.40824829  0.88798808  0.02851182]
 [-0.81649658  0.45889924  0.45840014]
 [ 0.40824829  0.0298104   0.88828846]]

Eigenvectors in descending order:

[0 2 1]
[[ 0.40824829  0.02851182  0.88798808]
 [-0.81649658  0.45840014  0.45889924]
 [ 0.40824829  0.88828846  0.0298104 ]]
